In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("../m3-caso_practico_numpy/videojuegos.csv")
df.head(2)

Rank               Name Platform    Year     Genre Publisher  NA_Sales  \
0     1         Wii Sports      Wii  2006.0    Sports  Nintendo     41.49   
1     2  Super Mario Bros.      NES  1985.0  Platform  Nintendo     29.08   

   EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     29.02      3.77         8.46         82.74  
1      3.58      6.81         0.77         40.24

In [20]:
df['Name'].values

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii', ...,
       'SCORE International Baja 1000: The Official Game', 'Know How 2',
       'Spirits & Spells'], dtype=object)

In [17]:
platforms = df['Platform'].values
platforms

array(['Wii', 'NES', 'Wii', ..., 'PS2', 'DS', 'GBA'], dtype=object)

In [21]:
years = df['Year'].values
years

array([2006., 1985., 2008., ..., 2008., 2010., 2003.])

In [22]:
genres = df['Genre'].values
genres

array(['Sports', 'Platform', 'Racing', ..., 'Racing', 'Puzzle',
       'Platform'], dtype=object)

In [23]:
publisher = df['Publisher'].values
publisher

array(['Nintendo', 'Nintendo', 'Nintendo', ..., 'Activision', '7G//AMES',
       'Wanadoo'], dtype=object)

In [24]:
df.head(1)

Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74

In [26]:
NA_sales = df['NA_Sales'].values
NA_sales

array([41.49, 29.08, 15.85, ...,  0.  ,  0.  ,  0.01])

In [27]:
EU_Sales = df['EU_Sales'].values
EU_Sales

array([29.02,  3.58, 12.88, ...,  0.  ,  0.01,  0.  ])

In [28]:
JP_Sales = df['JP_Sales'].values
JP_Sales

array([3.77, 6.81, 3.79, ..., 0.  , 0.  , 0.  ])

In [29]:
Other_Sales = df['Other_Sales'].values
Other_Sales

array([8.46, 0.77, 3.31, ..., 0.  , 0.  , 0.  ])

In [30]:
Global_Sales = df['Global_Sales'].values
Global_Sales

array([82.74, 40.24, 35.82, ...,  0.01,  0.01,  0.01])