In [2]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv("../m3-caso_practico_numpy/videojuegos.csv")
data.head(2)

Rank               Name Platform    Year     Genre Publisher  NA_Sales  \
0     1         Wii Sports      Wii  2006.0    Sports  Nintendo     41.49   
1     2  Super Mario Bros.      NES  1985.0  Platform  Nintendo     29.08   

   EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     29.02      3.77         8.46         82.74  
1      3.58      6.81         0.77         40.24

In [7]:
columna_rank = np.array(data['Rank'])
columna_name = np.array(data['Name'])
columna_platform = np.array(data['Platform'])
columna_year = np.array(data['Year'])
columna_genre = np.array(data['Genre'])
columna_publisher = np.array(data['Publisher'])
columna_na_sales = np.array(data['NA_Sales'])
columna_eu_sales = np.array(data['EU_Sales'])
columna_jp_sales = np.array(data['JP_Sales'])
columna_other_sales = np.array(data['Other_Sales'])
columna_global_sales = np.array(data['Global_Sales'])

In [8]:
print(columna_rank[:5])
print(columna_name[:5])
print(columna_platform[:5])
print(columna_year[:5])
print(columna_genre[:5])
print(columna_publisher[:5])
print(columna_na_sales[:5])
print(columna_eu_sales[:5])
print(columna_jp_sales[:5])
print(columna_other_sales[:5])
print(columna_global_sales[:5])

[1 2 3 4 5]
['Wii Sports' 'Super Mario Bros.' 'Mario Kart Wii' 'Wii Sports Resort'
 'Pokemon Red/Pokemon Blue']
['Wii' 'NES' 'Wii' 'Wii' 'GB']
[2006. 1985. 2008. 2009. 1996.]
['Sports' 'Platform' 'Racing' 'Sports' 'Role-Playing']
['Nintendo' 'Nintendo' 'Nintendo' 'Nintendo' 'Nintendo']
[41.49 29.08 15.85 15.75 11.27]
[29.02  3.58 12.88 11.01  8.89]
[ 3.77  6.81  3.79  3.28 10.22]
[8.46 0.77 3.31 2.96 1.  ]
[82.74 40.24 35.82 33.   31.37]


In [10]:
media = np.mean(columna_global_sales)
print("Media:", media)

Media: 0.5374406555006628


In [11]:
mediana = np.median(columna_global_sales)
print("Mediana:", mediana)

Mediana: 0.17


In [ ]:
from scipy.stats import mode
moda = np.mode(columna_global_sales)
print("Moda:", moda.mode[0])

In [13]:
desviacion_estandar = np.std(columna_global_sales)
print("Desviación estándar:", desviacion_estandar)

Desviación estándar: 1.5549810910296606


In [19]:
ventas_por_genero = data.groupby('Genre')['Global_Sales'].sum()
generos_top = ventas_por_genero.sort_values(ascending=False)
top_tres_generos = generos_top.head(3)
print("Los tres géneros de juegos con más ventas globales son:")
for genero, ventas in top_tres_generos.items():
    print(f"- {genero}: {ventas}")

Los tres géneros de juegos con más ventas globales son:
- Action: 1751.18
- Sports: 1330.93
- Shooter: 1037.37
