In [7]:
numbers = [1, 2, 3, 4]
numbers

[1, 2, 3, 4]

# Importar numpy

In [8]:
import numpy as np

In [9]:
arr = np.array([1, 4, 2, 5, 3])
arr

array([1, 4, 2, 5, 3])

In [10]:
x = np.arange(10)
x
            

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.random((3, 3))  # valores entre 0 y 1

array([[0.41424838, 0.51786055, 0.25438402],
       [0.09466398, 0.47098802, 0.83744587],
       [0.75415276, 0.67562226, 0.62044302]])

In [12]:
np.random.randint(0, 10, (3, 3))  # valores entre 0 y 10 excluido

array([[1, 3, 1],
       [3, 9, 1],
       [3, 5, 7]])

np.eye

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.empty

In [14]:
arr1 = np.empty(6)
arr1.ndim

1

## Atributos de arrays

In [15]:
np.random.seed(0)

In [16]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [17]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [20]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [21]:
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
print("dtype:", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12
dtype: int32
itemsize: 4 bytes
nbytes: 48 bytes


In [22]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [23]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


### Acceder a los elementos: indexación

In [24]:
x1

array([5, 0, 3, 3, 7, 9])

In [25]:
print(x1[0])
print(x1[1])
print(x1[2])

5
0
3


In [26]:
print(x1[-1])
print(x1[-2])
print(x1[-3])

9
7
3


In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
print(x2[0,0])
print(x2[0,1])
print(x2[0,2])
print(x2[0,3])
print(x2[1,0])
print(x2[1,1])
print(x2[1,2])
print(x2[2,3])

3
5
2
4
7
6
8
7
