In [18]:
import numpy as np

In [19]:
total_bill = np.genfromtxt('../csv_code/Data/tips.csv',
                        delimiter=',', skip_header=1,
                        usecols=(0), dtype=float)
tip = np.genfromtxt('../csv_code/Data/tips.csv',
                        delimiter=',', skip_header=1,
                        usecols=(1), dtype=float)

genre = np.genfromtxt('../csv_code/Data/tips.csv',
                        delimiter=',', skip_header=1,
                        usecols=(2), dtype=str)
smoker = np.genfromtxt('../csv_code/Data/tips.csv',
                        delimiter=',', skip_header=1,
                        usecols=(3), dtype=str)
day = np.genfromtxt('../csv_code/Data/tips.csv',
                        delimiter=',', skip_header=1,
                        usecols=(4), dtype=str)
time = np.genfromtxt('../csv_code/Data/tips.csv',
                        delimiter=',', skip_header=1,
                        usecols=(5), dtype=str)
size = np.genfromtxt('../csv_code/Data/tips.csv',
                        delimiter=',', skip_header=1,
                        usecols=(6), dtype=int)

                    


In [20]:
print(total_bill[:5])
print(tip[:5])
print(genre[:5])
print(smoker[:5])
print(day[:5])
print(time[:5])
print(size[:5])

[16.99 10.34 21.01 23.68 24.59]
[1.01 1.66 3.5  3.31 3.61]
['"Female"' '"Male"' '"Male"' '"Male"' '"Female"']
['"No"' '"No"' '"No"' '"No"' '"No"']
['"Sun"' '"Sun"' '"Sun"' '"Sun"' '"Sun"']
['"Dinner"' '"Dinner"' '"Dinner"' '"Dinner"' '"Dinner"']
[2 3 3 2 4]


## Categoricas

In [21]:
print(np.unique(genre))
print(np.unique(smoker))
print(np.unique(day))
print(np.unique(time))

['"Female"' '"Male"']
['"No"' '"Yes"']
['"Fri"' '"Sat"' '"Sun"' '"Thur"']
['"Dinner"' '"Lunch"']


In [22]:
import collections


print(collections.Counter(genre))
print(collections.Counter(smoker))
print(collections.Counter(day))
print(collections.Counter(time))

Counter({'"Male"': 157, '"Female"': 87})
Counter({'"No"': 151, '"Yes"': 93})
Counter({'"Sat"': 87, '"Sun"': 76, '"Thur"': 62, '"Fri"': 19})
Counter({'"Dinner"': 176, '"Lunch"': 68})


In [30]:
filter = np.logical_or(day == "Sat", day == "Sun")
day[filter][:5]

array([], dtype='<U6')

In [31]:
day[(day == "Sat") | (day == "Sun")][:5]

array([], dtype='<U6')

## Numéricas

In [25]:
# Columna total_bill
print(f"mean: {np.mean(total_bill)}")
print(f"median: {np.median(total_bill)}")
print(f"max: {np.max(total_bill)}")
print(f"min: {np.min(total_bill)}")
print(f"std: {np.std(total_bill)}")

mean: 19.78594262295082
median: 17.795
max: 50.81
min: 3.07
std: 8.884150577771132


### para redondear

In [26]:
print(f"mean: {np.around(np.mean(total_bill), 2)}")


mean: 19.79


In [33]:
# columna propina
print(f"mean: {np.mean(tip)}")
print(f"median: {np.median(tip)}")
print(f"max: {np.max(tip)}")
print(f"min: {np.min(tip)}")
print(f"std: {np.std(tip)}")

mean: 2.99827868852459
median: 2.9
max: 10.0
min: 1.0
std: 1.3807999538298954


In [34]:
# columna size
print(f"mean: {np.around(np.mean(size), 0)}")
print(f"mean: {np.mean(size)}")
print(f"median: {np.median(size)}")
print(f"max: {np.max(size)}")
print(f"min: {np.min(size)}")
print(f"std: {np.std(size)}")


mean: 3.0
mean: 2.569672131147541
median: 2.0
max: 6
min: 1
std: 0.9491488287193913


In [29]:
len(tip)

244