In [1]:
import numpy as np

In [8]:
names= np.genfromtxt('../dataset/vgsales.csv',
              usecols=(1), dtype=str, skip_header=1, 
              delimiter=',', invalid_raise=False)
names[:5]

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii',
       'Wii Sports Resort', 'Pokemon Red/Pokemon Blue'], dtype='<U132')

In [9]:
platform = np.genfromtxt('../dataset/vgsales.csv',
              usecols=(2), dtype=str, skip_header=1, 
              delimiter=',')
platform.shape

(16598,)

In [10]:
year= np.genfromtxt('../dataset/vgsales.csv',
              usecols=(3), dtype=int, skip_header=1, 
              delimiter=',')
year.shape

(16598,)

In [11]:
gernes = np.genfromtxt('../dataset/vgsales.csv',
              usecols=(4), dtype=str, skip_header=1, 
              delimiter=',')
gernes.shape

(16598,)

In [12]:
publishers = np.genfromtxt('../dataset/vgsales.csv',
              usecols=(5), dtype=str, skip_header=1, 
              delimiter=',')
publishers.shape


(16598,)

In [15]:
sales = np.genfromtxt('../dataset/vgsales.csv',
              usecols=(6, 7, 8, 9), dtype=float, skip_header=1, 
              delimiter=',')
sales.shape

(16598,)

In [16]:

# set_printoptions(suppress) quita valores especiales
np.set_printoptions(suppress=True)
sales

array([[41.49, 29.02,  3.77,  8.46],
       [29.08,  3.58,  6.81,  0.77],
       [15.85, 12.88,  3.79,  3.31],
       ...,
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.  ,  0.  ],
       [ 0.01,  0.  ,  0.  ,  0.  ]])

In [17]:
# Calcular ventas totales en horizontal con el 1
np.sum(sales, axis=1)

array([82.74, 40.24, 35.83, ...,  0.  ,  0.01,  0.01])

In [18]:
total_sales = np.sum(sales, axis=1)
total_sales

array([82.74, 40.24, 35.83, ...,  0.  ,  0.01,  0.01])

In [22]:
# para detectar si hay nan
isnan = np.isnan(total_sales)
isnan[isnan == True]

array([False, False, False, ..., False, False, False])

In [23]:
print(f"mean: {np.mean(total_sales)})")
print(f"median: {np.median(total_sales)}")
print(f"max: {np.min(total_sales)}")
print(f"min: {np.min(total_sales)}")
print(f"std. {np.std(total_sales)}")

mean: nan)
median: nan
max: nan
min: nan
std. nan


In [24]:
print(f"Hay NaN: {np.isnan(total_sales).any()}")
print(f"Hay infinito: {np.isinf(total_sales).any()}")
print(f"Hay infinito neg: {np.isneginf(total_sales).any()}")


Hay NaN: True
Hay infinito: False
Hay infinito neg: False


In [25]:
# contar cuantos NaN hay
len(total_sales[np.isnan(total_sales)])


123

In [28]:
# Reemplazar por 0 o -1
total_sales2 = np.nan_to_num(total_sales, nan=0)
print(f"{len(total_sales2)}")
print(f"{np.isnan(total_sales2).any()}") 


16598
False


In [29]:
# Calcular la media de total_sales sin nan
total_sales_3 = np.nansum(sales, axis=1)
np.isnan(total_sales_3).any()


False

In [30]:
np.isnan(sales).any()
np.nan_to_num(sales, nan=0)

array([[41.49, 29.02,  3.77,  8.46],
       [29.08,  3.58,  6.81,  0.77],
       [15.85, 12.88,  3.79,  3.31],
       ...,
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.01,  0.  ,  0.  ],
       [ 0.01,  0.  ,  0.  ,  0.  ]])

In [31]:
sales_good = sales[~(np.isnan(sales))]
sales_good

array([41.49, 29.02,  3.77, ...,  0.  ,  0.  ,  0.  ])

In [33]:
# True significa que hay nulos(NaN)
print(sales.shape)
print(np.isnan(sales).any())

(16598, 4)
True


In [36]:
mean_per_column = np.nanmean(sales,  axis=0)
mask = np.isnan(sales)
for i in range(sales.shape[1]):
    sales[mask[:, i], i] = mean_per_column[i]

In [35]:
print(sales.shape)
print(np.isnan(sales).any()) #  false singifica que no hay NaN

(16598, 4)
False
